/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AkumulasiRouteImport } from './routes/akumulasi'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as PinjamRouteImport } from './routes/pinjam'
import { Route as PortofolioRouteImport } from './routes/portofolio'
import { Route as ProyekRouteImport } from './routes/proyek'
import { Route as RekapRouteImport } from './routes/rekap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkumulasiRoute = AkumulasiRouteImport.update({
  id: '/akumulasi',
  path: '/akumulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const PinjamRoute = PinjamRouteImport.update({
  id: '/pinjam',
  path: '/pinjam',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofolioRoute = PortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyekRoute = ProyekRouteImport.update({
  id: '/proyek',
  path: '/proyek',
  getParentRoute: () => rootRouteImport,
} as any)
const RekapRoute = RekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akumulasi': typeof AkumulasiRoute
  '/keuangan': typeof KeuanganRoute
  '/pinjam': typeof PinjamRoute
  '/portofolio': typeof PortofolioRoute
  '/proyek': typeof ProyekRoute
  '/rekap': typeof RekapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akumulasi': typeof AkumulasiRoute
  '/keuangan': typeof KeuanganRoute
  '/pinjam': typeof PinjamRoute
  '/portofolio': typeof PortofolioRoute
  '/proyek': typeof ProyekRoute
  '/rekap': typeof RekapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akumulasi': typeof AkumulasiRoute
  '/keuangan': typeof KeuanganRoute
  '/pinjam': typeof PinjamRoute
  '/portofolio': typeof PortofolioRoute
  '/proyek': typeof ProyekRoute
  '/rekap': typeof RekapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akumulasi'
    | '/keuangan'
    | '/pinjam'
    | '/portofolio'
    | '/proyek'
    | '/rekap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akumulasi'
    | '/keuangan'
    | '/pinjam'
    | '/portofolio'
    | '/proyek'
    | '/rekap'
  id:
    | '__root__'
    | '/'
    | '/akumulasi'
    | '/keuangan'
    | '/pinjam'
    | '/portofolio'
    | '/proyek'
    | '/rekap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkumulasiRoute: typeof AkumulasiRoute
  KeuanganRoute: typeof KeuanganRoute
  PinjamRoute: typeof PinjamRoute
  PortofolioRoute: typeof PortofolioRoute
  ProyekRoute: typeof ProyekRoute
  RekapRoute: typeof RekapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akumulasi': {
      id: '/akumulasi'
      path: '/akumulasi'
      fullPath: '/akumulasi'
      preLoaderRoute: typeof AkumulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinjam': {
      id: '/pinjam'
      path: '/pinjam'
      fullPath: '/pinjam'
      preLoaderRoute: typeof PinjamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofolio': {
      id: '/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PortofolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyek': {
      id: '/proyek'
      path: '/proyek'
      fullPath: '/proyek'
      preLoaderRoute: typeof ProyekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekap': {
      id: '/rekap'
      path: '/rekap'
      fullPath: '/rekap'
      preLoaderRoute: typeof RekapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkumulasiRoute: AkumulasiRoute,
  KeuanganRoute: KeuanganRoute,
  PinjamRoute: PinjamRoute,
  PortofolioRoute: PortofolioRoute,
  ProyekRoute: ProyekRoute,
  RekapRoute: RekapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
